### ISSUE TITLE
addCohortIntersect - restrict to between a cohort

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/PatientProfiles#296]
For generating table one etc, it could be nice to have the option to limit cohort intersection to between the cohort start and cohort end of the index cohort

**Comment by catalamarti** [comment]
Hi @edward-burn I don't understand the feature quite well can you prove an example?

**Comment by tiozab** [comment]
@catalamarti this situation arose from the pregnancy cohorts. where the pregnancy start date is the cohort start date, and where the cohort end date should be the pregnancy end date, thereby, we could assess intersects in the time frame of a pregnancy (i.e. because it is very hard to work with the window in this case). Is it understandable now? @edward-burn, I clarified it for you ;-)

**Comment by catalamarti** [comment]
Hi @KimLopezGuell  can you take care of this we will add an option: value = "overlap" and the subsequent function addCohortIntersectOverlap

**Comment by KimLopezGuell** [comment]
Would the function addCohortIntersectOverlap add a specific type of column (i.e. flag, count, days, date) or would we add the option of which of those?

**Comment by tiozab** [comment]
@KimLopezGuell, while you are at it: would it be also possible to have a combination of cohort and window? for example, with pregnancies, we would be interested in trimesters as well. therefore, from cohort start until 90 days (first trimester) is easy with the existing version, "during pregnancy" will be possible with the new cohortoverlap functionality, but, if we want to know in the third trimester, we would need to have "180 days after cohort start until cohort end" (maybe it would be cool to have an argument by which we can have an "offset" on the start date), and for second semester, we would actually need to have s.th. like 90 days to 180 days after start or cohort end (whichever was first)... I know this may be a lot, but worth thinking about. @catalamarti, what do you think?

**Comment by tiozab** [comment]
@KimLopezGuell that is actually perfect, I think, because that means that we can do select a "window" that consists of days or cohort end date. I was also thinking that it would be ok to write bespoke code for this edge case of second and third trimester ;-) but it seems you killed two flies in one go :-) Thank you!

**Comment by catalamarti** [comment]
this was addressed in #305 with a new parameter
